# WireGuard Configuration Template
# Generated by Terraform - Do not edit manually

[Interface]
PrivateKey = ${interface_private_key}
Address = ${interface_address}
%{ if listen_port > 0 ~}
ListenPort = ${listen_port}
%{ endif ~}
%{ if is_server ~}

# Optional: Enable IP forwarding for routing
PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostUp = iptables -A FORWARD -o %i -j ACCEPT
PostDown = iptables -D FORWARD -i %i -j ACCEPT
PostDown = iptables -D FORWARD -o %i -j ACCEPT
%{ endif ~}

[Peer]
PublicKey = ${peer_public_key}
AllowedIPs = ${peer_allowed_ips}
%{ if peer_endpoint != "" ~}
Endpoint = ${peer_endpoint}
%{ endif ~}
%{ if persistent_keepalive > 0 ~}
PersistentKeepalive = ${persistent_keepalive}
%{ endif ~}
